<template>
  <form class="deposit" action="">
    <div class="alert alert-status modal-card connection-details">
      <header class="modal-card-head">
        <p class="modal-card-title">
          Lightning Connection Details
        </p>
      </header>
      <section class="modal-card-body">
        <div class="address-info">
          <div class="address-info-left">
            <p>Send this code to others who want to open a custom channel with your Lightning node.</p>

            <div class="qr-code"
              v-clipboard:copy="lnAddress.code"
              v-clipboard:success="onCopy"
              v-clipboard:error="onError">
              <qr-code :text="lnAddress.code" size="320"></qr-code>
              <p>{{lnAddress.code}}</p>
            </div>
          </div>
          <br>
        </div>

        <div class="discovery-problem" v-if="!lnAddress.autoGenerated">
          <hr>

          <h2 class="is-danger">
            <img src="~assets/icon-circle-warning.svg" alt="error">

            There's a Discovery Problem
          </h2>

          <p>
            Your node couldn't automatically make itself visible to the Lightning network. To fix this:
          </p>

          <p>
            1. Enable UPnP in your router settings, then restart your node and check your connection visibility again here.
          </p>

          <p>
            2. If you still see this error, set up port forwarding <a href="https://keys.casa/node-help/#port-forwarding" target="_blank" rel="noopener">using this guide</a>, then click "Continue with port forwarding" below.
          </p>
        </div>
      </section>
      <footer class="modal-card-foot">
        <a class="button is-gray" type="button" @click="$parent.close()">
          Close
        </a>

        <!-- Don't allow overwriting connection details if an onion address exists -->
        <a v-if="lnAddress.autoGenerated && !lnAddress.onion" class="button is-casa" type="button" @click="editConnection()">
          Edit Connection Details
        </a>

        <a v-else-if="!lnAddress.onion" class="button is-casa" type="button" @click="editConnection()">
          Continue with Port Forwarding
        </a>
      </footer>
    </div>
  </form>
</template>

<script>
import axios from 'axios';
import ConnectionDetails from '@/components/Lightning/Modals/ConnectionDetails';

export default {
  name: 'ConnectionCode',
  props: ['lnAddress'],

  methods: {
    editConnection() {
      this.$parent.close();
      this.$modal.open({parent: this, component: ConnectionDetails, hasModalCard: true, props: {lnAddress: this.lnAddress}});
    },

    onCopy: function(e) {
      this.$toast.open({duration: 3000, message:`Copied ${e.text}`});
    },
    onError: function(e) {
      console.error('Failed to copy address text', e);
    }
  }
};
</script>
